# devicedevex.azurecr.io/public/iot-device-cube:1.0.0-azure-c-app-20190411-ubuntu-arm64
FROM devicedevex.azurecr.io/public/iot-device-cube:1.0.0-azure-c-sdk-20190411-ubuntu-arm64

COPY compile_app.sh /work/