<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>colorizedChannel</string>
        <key>scopeName</key>
        <string>text.channel.colorized</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>channel.colorized.info</string>
                <key>match</key>
                <string>(\[Start\]|\[Done\])(.*)</string>
                <key>captures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>channel.colorized.warn</string>
                <key>match</key>
                <string>(\[Warn\])(.+)</string>
                <key>captures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>token.warn-token</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>channel.colorized.error</string>
                <key>match</key>
                <string>(\[Error\])(.+)</string>
                <key>captures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>token.error-token</string>
                    </dict>
                </dict>
            </dict>
        </array>
    </dict>
</plist>