# devicedevex.azurecr.io/public/iot-device-cube:1.0.0-azure-c-app-20190411-ubuntu-arm64
ARG base_image_tag=devicedevex.azurecr.io/public/iot-device-cube:iot-device-cube:1.0.0-azure-c-sdk-20190411-ubuntu-x86
FROM devicedevex.azurecr.io/public/iot-device-cube:${base_image_tag}

COPY compile_app.sh /work/